### ISSUE TITLE
`AttributeError`: Can only use `.cat` accessor with a 'category' dtype

### ISSUE THREAD

**Issue by jakirkham** [sophiamyang/condastats#20]
* condastats version: 0.2.1
* Python version: 3.11.9
* Operating System: macOS 14.4.1 on Apple M1 Pro

<details>

```yaml
name: condastats
channels:
  - conda-forge
dependencies:
  - aiobotocore=2.12.2=pyhd8ed1ab_0
  - aiohttp=3.9.5=py311h05b510d_0
  - aioitertools=0.11.0=pyhd8ed1ab_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.18=h382b9c6_0
  - aws-c-cal=0.6.11=hd34e5fa_0
  - aws-c-common=0.9.15=h93a5062_0
  - aws-c-compression=0.2.18=hd34e5fa_3
  - aws-c-event-stream=0.4.2=h247c08a_8
  - aws-c-http=0.8.1=hf9e830b_10
  - aws-c-io=0.14.7=h33d81b3_6
  - aws-c-mqtt=0.10.4=h5f4abda_0
  - aws-c-s3=0.5.7=h7644b7e_2
  - aws-c-sdkutils=0.1.15=hd34e5fa_3
  - aws-checksums=0.1.18=hd34e5fa_3
  - aws-crt-cpp=0.26.8=h7541583_2
  - aws-sdk-cpp=1.11.267=h18943f6_7
  - bokeh=3.4.1=pyhd8ed1ab_0
  - botocore=1.34.51=pyge310_1234567_0
  - brotli-python=1.1.0=py311ha891d26_1
  - bzip2=1.0.8=h93a5062_5
  - c-ares=1.28.1=h93a5062_0
  - ca-certificates=2024.2.2=hf0a4a13_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - condastats=0.2.1=pyhd8ed1ab_0
  - contourpy=1.2.1=py311hcc98501_0
  - cramjam=2.8.3=py311h94f323b_0
  - cytoolz=0.12.3=py311h05b510d_0
  - dask=2024.2.1=pyhd8ed1ab_0
  - dask-core=2024.2.1=pyhd8ed1ab_1
  - distributed=2024.2.1=pyhd8ed1ab_0
  - freetype=2.12.1=hadb7bae_2
  - frozenlist=1.4.1=py311h05b510d_0
  - fsspec=2024.3.1=pyhca7485f_0
  - gflags=2.2.2=hc88da5d_1004
  - glog=0.7.0=hc6770e3_0
  - icu=73.2=hc8870d7_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - krb5=1.21.2=h92f50d5_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20240116.2=cxx17_hebf3989_0
  - libarrow=15.0.2=hea125af_6_cpu
  - libarrow-acero=15.0.2=h3f3aa29_6_cpu
  - libarrow-dataset=15.0.2=h3f3aa29_6_cpu
  - libarrow-flight=15.0.2=h224147a_6_cpu
  - libarrow-flight-sql=15.0.2=hb630850_6_cpu
  - libarrow-gandiva=15.0.2=h3b9069c_6_cpu
  - libarrow-substrait=15.0.2=hd92e347_6_cpu
  - libblas=3.9.0=22_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=22_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.7.1=h2d989ff_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.20=h93a5062_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libgoogle-cloud=2.23.0=hbebe991_1
  - libgoogle-cloud-storage=2.23.0=h8a76758_1
  - libgrpc=1.62.2=h9c18a4f_0
  - libiconv=1.17=h0d3ecfb_2
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=22_osxarm64_openblas
  - libllvm16=16.0.6=haab561b_3
  - libnghttp2=1.58.0=ha4dd798_1
  - libopenblas=0.3.27=openmp_h6c19121_0
  - libparquet=15.0.2=h5304c63_6_cpu
  - libpng=1.6.43=h091b4b1_0
  - libprotobuf=4.25.3=hbfab5d5_0
  - libre2-11=2023.09.01=h7b2c953_2
  - libsqlite=3.45.3=h091b4b1_0
  - libssh2=1.11.0=h7a5bd25_0
  - libthrift=0.19.0=h026a170_1
  - libtiff=4.6.0=h07db509_3
  - libutf8proc=2.8.0=h1a8c8d9_0
  - libwebp-base=1.4.0=h93a5062_0
  - libxcb=1.15=hf346824_0
  - libxml2=2.12.6=h0d0cfa8_2
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=18.1.5=hde57baf_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py311hd44b8e9_0
  - lz4-c=1.9.4=hb7217d7_0
  - markupsafe=2.1.5=py311h05b510d_0
  - msgpack-python=1.0.7=py311hd03642b_0
  - multidict=6.0.5=py311he2be06e_0
  - ncurses=6.4.20240210=h078ce10_0
  - numpy=1.26.4=py311h7125741_0
  - openjpeg=2.5.2=h9f1df11_0
  - openssl=3.3.0=h0d3ecfb_0
  - orc=2.0.0=h4aad248_1
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=1.5.3=py311h4eec4a9_1
  - partd=1.4.1=pyhd8ed1ab_0
  - pillow=10.3.0=py311h0b5d0a1_0
  - pip=24.0=pyhd8ed1ab_0
  - psutil=5.9.8=py311h05b510d_0
  - pthread-stubs=0.4=h27ca646_1001
  - pyarrow=15.0.2=py311h5ff715f_6_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.9=h932a869_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-snappy=0.7.1=pyh48db8ab_1
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311heffc1b2_1
  - re2=2023.09.01=h4cba328_2
  - readline=8.2=h92ec313_1
  - s3fs=2024.3.1=pyhd8ed1ab_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.0=hd04f947_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - tblib=3.0.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.4=py311h05b510d_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - urllib3=2.0.7=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - wrapt=1.16.0=py311h05b510d_0
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xyzservices=2024.4.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.9.4=py311h05b510d_0
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zstd=1.5.6=hb46c0d2_0
```

</details>

### Description

Tried to query statistics on a recent `pandas` release and got a traceback. Originally was using Pandas 2. So downgraded to Pandas 1 in case that was the issue, but the error still came up

### What I Did

```sh
condastats overall pandas --start_month 2024-03 --end_month 2024-04 --monthly
```

```python
Traceback (most recent call last):
  File "/Users/jkirkham/miniforge/envs/condastats/bin/condastats", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/jkirkham/miniforge/envs/condastats/lib/python3.11/site-packages/condastats/cli.py", line 387, in main
    overall(
  File "/Users/jkirkham/miniforge/envs/condastats/lib/python3.11/site-packages/condastats/cli.py", line 88, in overall
    df["pkg_name"] = df["pkg_name"].cat.remove_unused_categories()
                     ^^^^^^^^^^^^^^^^^^
  File "/Users/jkirkham/miniforge/envs/condastats/lib/python3.11/site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkirkham/miniforge/envs/condastats/lib/python3.11/site-packages/pandas/core/accessor.py", line 182, in __get__
    accessor_obj = self._accessor(obj)
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/jkirkham/miniforge/envs/condastats/lib/python3.11/site-packages/pandas/core/arrays/categorical.py", line 2849, in __init__
    self._validate(data)
  File "/Users/jkirkham/miniforge/envs/condastats/lib/python3.11/site-packages/pandas/core/arrays/categorical.py", line 2858, in _validate
    raise AttributeError("Can only use .cat accessor with a 'category' dtype")
AttributeError: Can only use .cat accessor with a 'category' dtype. Did you mean: 'at'?
```

Note: There was new data uploaded recently ( https://github.com/ContinuumIO/anaconda-package-data/issues/45 ). So it is possible this comes up due to the data structure itself

**Comment by cappadona** [comment]
Hi @jakirkham. Thanks for reporting this.

* I was able to reproduce this, as I mentioned in https://github.com/ContinuumIO/anaconda-package-data/issues/45#issuecomment-2115327171

> ... it looks like the new parquet files for March and April 2024 are missing some pandas specific properties in the file metadata that are expected by condastats.

I've uploaded new versions of the monthly data to the s3 bucket for March and April 2024 which include the pandas properties in the parquet metadata and then re-ran your `condastats` command successfully.

Will you give this another try when you get a chance and report back here? If successful, I'll apply the same changes to the hourly data as well.

## Before
Notice that if we use an earlier month as our start, we don't hit the error
<img width="851" alt="Screenshot 2024-05-16 at 10 05 33 AM" src="https://github.com/sophiamyang/condastats/assets/409842/a0a5b1a2-a686-4497-b369-19cbcca47bbf">


## After
<img width="663" alt="Screenshot 2024-05-16 at 10 15 06 AM" src="https://github.com/sophiamyang/condastats/assets/409842/c2c6aadd-df07-4b2f-ae70-a219aca4b81e">

**Comment by cappadona** [comment]
Hi @jakirkham. Have you had a chance to try `condastats` again with the March or April 2024 monthly data?

**Comment by jakirkham** [comment]
Sorry I had not

Trying now, it does appear to be working! 🥳 

```
% condastats overall pandas --start_month 2024-03 --end_month 2024-04 --monthly
pkg_name  time   
pandas    2024-03    8548771
          2024-04    7781921
Name: counts, dtype: int64
```

Thanks Nick! 🙏

Let's close this out ✅
