### ISSUE TITLE
ImportError while runnning condastats despite packages installed

### ISSUE THREAD

**Issue by jhillairet** [sophiamyang/condastats#6]
* condastats version: 0.1.5
* Python version: 3.8.11
* Operating System: Linux or Windows

### Description

After installing `condastats` using `conda install -c conda-forge condastats` [OK], running condastats leads to the following error:

```
$ condastats overall numpy
Traceback (most recent call last):
  File "/home/hillairet/miniconda3/lib/python3.8/site-packages/fsspec/registry.py", line 219, in get_filesystem_class
    register_implementation(protocol, _import_class(bit["class"]))
  File "/home/hillairet/miniconda3/lib/python3.8/site-packages/fsspec/registry.py", line 242, in _import_class
    mod = importlib.import_module(mod)
  File "/home/hillairet/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hillairet/miniconda3/lib/python3.8/site-packages/s3fs/__init__.py", line 1, in <module>
    from .core import S3FileSystem, S3File
  File "/home/hillairet/miniconda3/lib/python3.8/site-packages/s3fs/core.py", line 12, in <module>
    from fsspec.asyn import AsyncFileSystem, sync, sync_wrapper, maybe_sync
ImportError: cannot import name 'maybe_sync' from 'fsspec.asyn' (/home/hillairet/miniconda3/lib/python3.8/site-packages/fsspec/asyn.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hillairet/miniconda3/bin/condastats", line 10, in <module>
    sys.exit(main())
  File "/home/hillairet/miniconda3/lib/python3.8/site-packages/condastats/cli.py", line 382, in main
    overall(
  File "/home/hillairet/miniconda3/lib/python3.8/site-packages/condastats/cli.py", line 61, in overall
    df = dd.read_parquet(
  File "/home/hillairet/miniconda3/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py", line 298, in read_parquet
    fs, _, paths = get_fs_token_paths(path, mode="rb", storage_options=storage_options)
  File "/home/hillairet/miniconda3/lib/python3.8/site-packages/fsspec/core.py", line 636, in get_fs_token_paths
    cls = get_filesystem_class(protocol)
  File "/home/hillairet/miniconda3/lib/python3.8/site-packages/fsspec/registry.py", line 221, in get_filesystem_class
    raise ImportError(bit["err"]) from e
ImportError: Install s3fs to access S3
```
despite that `s3fs` and `fsspec` packages are already installed:

```
$ conda list s3fs
# Name                    Version                   Build  Channel
s3fs                      0.5.1                      py_0    conda-forge
fsspec                    2021.10.0          pyhd8ed1ab_0    conda-forge
```

The problem seems to come from changes in `fsspec`:

```
>>> from fsspec.asyn import maybe_sync
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'maybe_sync' from 'fsspec.asyn' (/home/hillairet/miniconda3/lib/python3.8/site-packages/fsspec/asyn.py)

```

**Comment by sophiamyang** [comment]
Thanks for the bug report!  Please upgrade `s3fs` to a newer version--at least 0.6.0, but preferably a version that matches the version of `fsspec`.  For example, `conda install -c conda-forge s3fs=2021.10.0`.

CC @martindurant.  When creating a new conda environment, `conda create -n condastats python=3.8 condastats`, `fsspec` version 2021.10.0 and `s3fs` version 0.5.1 are installed, but these are incompatible.

The next time I update `condastats`, I will specify minimum versions for both `s3fs` and `fsspec` to avoid this.

**Comment by jhillairet** [comment]
Thank you. It works after removing `condastats`, installing the proper version of `s3fs` and reinstalling `condatstats` .
