### ISSUE TITLE
Unable to retrieve any data (access denied)

### ISSUE THREAD

**Issue by ragonneau** [sophiamyang/condastats#8]
* condastats version: 0.1.5
* Python version: 3.9.5 (default, May 19 2021, 11:32:47)  [GCC 9.3.0]
* Operating System: Linux-5.11.0-41-generic-x86_64-with-Ubuntu-20.04-focal

### Description

The S3 server cannot be accessed.

### What I Did

```
(venv) tmr@niphredil:~/PycharmProjects/pdfo.github.io/static/scripts/stats$ condastats overall pdfo
Traceback (most recent call last):
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/s3fs/core.py", line 261, in _call_s3
    out = await method(**additional_kwargs)
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/aiobotocore/client.py", line 180, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/bin/condastats", line 8, in <module>
    sys.exit(main())
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/condastats/cli.py", line 382, in main
    overall(
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/condastats/cli.py", line 85, in overall
    df = df.compute()
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/base.py", line 288, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/base.py", line 571, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/optimization.py", line 969, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/core.py", line 113, in _execute_task
    return [_execute_task(a, cache) for a in arg]
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/core.py", line 113, in <listcomp>
    return [_execute_task(a, cache) for a in arg]
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/dataframe/io/parquet/core.py", line 87, in __call__
    return read_parquet_part(
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/dataframe/io/parquet/core.py", line 422, in read_parquet_part
    dfs = [
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/dataframe/io/parquet/core.py", line 423, in <listcomp>
    func(fs, rg, columns.copy(), index, **toolz.merge(kwargs, kw))
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/dask/dataframe/io/parquet/fastparquet.py", line 953, in read_partition
    parquet_file = ParquetFile(
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/fastparquet/api.py", line 109, in __init__
    basepath, fmd = metadata_from_many(fn, verify_schema=verify,
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/fastparquet/util.py", line 155, in metadata_from_many
    pfs = [api.ParquetFile(fn, open_with=open_with) for fn in file_list]
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/fastparquet/util.py", line 155, in <listcomp>
    pfs = [api.ParquetFile(fn, open_with=open_with) for fn in file_list]
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/fastparquet/api.py", line 133, in __init__
    self._parse_header(f, verify)
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/fastparquet/api.py", line 176, in _parse_header
    head_size = struct.unpack('<i', f.read(4))[0]
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/fsspec/spec.py", line 1565, in read
    out = self.cache._fetch(self.loc, self.loc + length)
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/fsspec/caching.py", line 377, in _fetch
    self.cache = self.fetcher(start, bend)
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/s3fs/core.py", line 1896, in _fetch_range
    return _fetch_range(
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/s3fs/core.py", line 2038, in _fetch_range
    resp = fs.call_s3(
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/fsspec/asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/fsspec/asyn.py", line 71, in sync
    raise return_result
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/home/tmr/PycharmProjects/pdfo.github.io/static/scripts/stats/venv/lib/python3.9/site-packages/s3fs/core.py", line 281, in _call_s3
    raise err
PermissionError: Access Denied
```

**Comment by sophiamyang** [comment]
Thanks for letting me know. It should be fixed now. Let me know if you still see issues. Thanks!

**Comment by ragonneau** [comment]
@sophiamyang It works perfectly, thank you very much!
